AlienOutputDirs: [
  /alice/cern.ch/user/a/alihyperloop/jobs/0355/hy_3552403/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0355/hy_3552402/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0355/hy_3552384/AOD,/alice/cern.ch/user/a/alihyperloop/jobs/0355/hy_3552383/AOD
]
LocalPath: /home/wuct/MetaData/DATA/OO/apass2/corr/tlook_MY_small/ME
ForceStage: False # in case files are not merged properly, force downloading staged files
FileName: AO2D.root
# AnalysisResults.root
# AO2D.root
# AA for AnalysisResults.root and AO2D.root